name: cinemapedia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^2.0.4
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_native_splash: ^2.2.19
  flutter_riverpod: ^2.3.3
  flutter_staggered_grid_view: ^0.6.2
  go_router: ^6.5.5
  intl: ^0.18.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-icon-2.jpeg"
  min_sdk_android: 21

flutter_native_splash:
  color: "#252829"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/icons/
